### PR TITLE
Fix space in username issue

### PR DESCRIPTION
**Pull request by BrennanConroy**
Should fix the problems at the end of this issue #190 

@anurse

### CODE REVIEW

**Comment by anurse** [comment]
:shipit:

**Comment by danielcrenna** [comment]
This is still happening with the published RC1 bits. Do you know when this will make it into the distro?

**Comment by BrennanConroy** [comment]
This is fixed in RC2 bits, `dnvm update-self`

**Comment by danielcrenna** [comment]
The issue with that is that the broken spaces actually prevents `dnvm update-self` for the same reason.

Where the user is "Daniel Crenna", `update-self` fails

**Comment by BrennanConroy** [comment]
You'll have to manually update then.

**Comment by danielcrenna** [comment]
Sure, where are the bits?

**Comment by BrennanConroy** [comment]
https://github.com/aspnet/Home/dnvm.cmd and https://github.com/aspnet/Home/dnvm.ps1 but for this issue specifically you only really need to replace the cmd

**Comment by danielcrenna** [comment]
Yes, that was the ticket. Thank you for leaving that there for myself and
others.

**Comment by rclabo** [comment]
I have the same problem due to a space in my username.  I need to manually update my dnvm.cmd file apparently.  the links that @BrennanConroy posted a couple weeks ago now return 404 errors.  Where can I get the dnvm.cmd file now to manually update mine?

**Comment by danielcrenna** [comment]
@rclabo they always 404'd but you can hit the main repository that the link
alludes to and find them in root directory

**Comment by rclabo** [comment]
@danielcrenna Thanks!

**Comment by danielcrenna** [comment]
@rclabo Looks like they moved things around slightly but might have luck at https://github.com/aspnet/dnvm/tree/dev/src

**Pull request merged**
